import 'dart:io';

import '../../models/ass_style.dart';
import '../../models/merge_options.dart';
import '../../models/subtitle_cue.dart';
import 'time_util.dart';

class AssWriter {
  static Future<File> write({
    required String path,
    required List<SubtitleCue> cues,
    required MergeOptions options,
    String title = 'dual-sub-merge',
  }) async {
    final styles = options.styleLines
        .map(AssStyle.tryParse)
        .whereType<AssStyle>()
        .toList();
    if (styles.isEmpty) {
      styles.addAll(StyleCatalog.defaults());
    }

    final buf = StringBuffer()
      ..writeln('[Script Info]')
      ..writeln('; Script generated by dual-sub-merge')
      ..writeln('Title: $title')
      ..writeln('ScriptType: v4.00+')
      ..writeln('WrapStyle: 0')
      ..writeln('ScaledBorderAndShadow: yes')
      ..writeln('PlayResX: ${options.playResX}')
      ..writeln('PlayResY: ${options.playResY}')
      ..writeln()
      ..writeln('[V4+ Styles]')
      ..writeln(
        'Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding',
      );
    for (final s in styles) {
      buf.writeln(s.line);
    }
    buf
      ..writeln()
      ..writeln('[Events]')
      ..writeln('Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text');

    final sorted = [...cues]..sort((a, b) {
        final c = a.startMs.compareTo(b.startMs);
        if (c != 0) return c;
        return _styleRank(a.outputStyle).compareTo(_styleRank(b.outputStyle));
      });

    for (final cue in sorted) {
      final style = cue.outputStyle.isEmpty ? StyleCatalog.chinese : cue.outputStyle;
      buf.writeln(
        'Dialogue: 0,${TimeUtil.formatAss(cue.startMs)},${TimeUtil.formatAss(cue.endMs)},$style,,0,0,0,,${cue.text}',
      );
    }

    final file = File(path);
    await file.parent.create(recursive: true);
    await file.writeAsString(buf.toString(), flush: true);
    return file;
  }

  static int _styleRank(String style) {
    if (style == StyleCatalog.lyric) return 0;
    if (style == StyleCatalog.annotation) return 1;
    if (style == StyleCatalog.foreign) return 2;
    if (style == StyleCatalog.chinese) return 3;
    return 9;
  }
}
